### ISSUE TITLE
default discover.el keybinds conflict with some other keybinds in the default config

### ISSUE THREAD

**Issue by SidneyMillen** [isomatter-labs/axiom#6]
**Describe the bug**
Some discover.el binds, particularly C-x r (makey-key-mode-popup-rectangles) and M-s (makey-key-mode-popup-isearch) for me, conflict with some of the consult binds like C-x r b for consult-bookmark, and all of the M-s search map bindings

**To Reproduce**
Enable global-discover-mode (already enabled in default config)

**Expected behavior**
Conflicting binds should be disabled or remapped so that other keybinds set in the default configuration work as expected

**Comment by scrimbles** [comment]
Apparently this is a [known issue with `discover.el`](https://github.com/mickeynp/discover.el/issues/14)

`discover.el` is mostly redundant since Starmacs already uses `which-key`, and I think only added prompts on dired-mode, which are probably better left to googling anyhow.

**Comment by scrimbles** [comment]
To remove this behavior, I will remove `discover.el` from the config

**Comment by SidneyMillen** [comment]
There is a conflict with `paredit` and the `M-s` map as well. `paredit-splice-sexp` is bound to `M-s` by default which makes the map inaccessible.
